### ISSUE TITLE
性能优化

### ISSUE THREAD

**Issue by Colafornia** [pinggod/gatsby-theme-wink#1]
Hello, 我正尝试使用这个主题，部署过之后用 lighthouse 测试发现有些性能优化点可以做，有计划做一些改进吗？

这是主题 demo 页的测试结果：

![image](https://user-images.githubusercontent.com/13252625/66726489-426f9b80-ee6c-11e9-909c-addd260b6e4a.png)

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwink.rexlnt.com

**Comment by pinggod** [comment]
@Colafornia 感谢提出性能优化的建议，在你提供的测试结果项中，除「Remove unused CSS」一项之外，我在本地开发过程中都有遇到，但现在还没有更好的解决方案。目前主题是支持 PWA 和 Responsive Images 的，之所以出现性能问题主要有两个原因，一是 Demo 托管在 Netlify，国内访问响应较慢，二是 Demo 图片下载自 https://unsplash.com 并使用了原图，体积经压缩后仍然较大，这两个因素导致整体页面响应较慢，暂无优秀解法，如你有更好方式，欢迎 PR！下图是 VPN 后在国内访问的测试结果，核心瓶颈在页面资源较大响应较慢，未复现「Remove unused CSS」问题：

![image](https://user-images.githubusercontent.com/9530963/66805997-f77f8200-ef58-11e9-888a-57c568fe822a.png)

**Comment by Colafornia** [comment]
我也是用了 Netlify 做持续集成，但是国内速度太不理想，就还是切换到了 cloudflare，现在墙内外访问速度都“稳定的不是特别慢”😐

感谢回复，很好看的主题！

我尝试做些优化试试~
